import type { CategoryTree } from '../types/tool'

export const categoryTree: CategoryTree[] = [
  {
    id: 'all',
    name: '全部资源',
    description: '所有推荐工具和资源',
    icon: 'Hash',
    count: 104,
  },
  {
    id: 'dev-tools',
    name: '开发工具',
    description: '代码编辑、调试、构建、浏览器插件等开发工具',
    icon: 'Wrench',
    count: 16,
    children: [
      { id: 'dev-editor', name: '代码编辑器', description: '', icon: 'Code', count: 4 },
      { id: 'dev-online', name: '在线运行环境', description: '', icon: 'Globe', count: 4 },
      { id: 'dev-debug', name: '调试工具', description: '', icon: 'Bug', count: 0 },
      { id: 'dev-format', name: '代码格式化', description: '', icon: 'AlignLeft', count: 0 },
      { id: 'dev-build', name: '编译构建', description: '', icon: 'Hammer', count: 0 },
      { id: 'dev-package', name: '包管理工具', description: '', icon: 'Package', count: 0 },
      { id: 'browser-main', name: '主流浏览器', description: '', icon: 'Chrome', count: 2 },
      { id: 'browser-plugin', name: '开发插件', description: '', icon: 'Puzzle', count: 2 },
      { id: 'browser-performance', name: '性能分析', description: '', icon: 'Activity', count: 2 },
      { id: 'browser-proxy', name: '抓包工具', description: '', icon: 'Network', count: 2 },
    ],
  },
  {
    id: 'framework',
    name: '框架 & 组件',
    description: '主流框架、UI库、工具函数库等',
    icon: 'Layers',
    count: 8,
    children: [
      { id: 'framework-main', name: '主流框架', description: '', icon: 'LayoutGrid', count: 8 },
      { id: 'framework-ui', name: 'UI组件库', description: '', icon: 'Palette', count: 0 },
      {
        id: 'framework-utils',
        name: '工具函数库',
        description: '',
        icon: 'FunctionSquare',
        count: 0,
      },
      { id: 'framework-animation', name: '动画库', description: '', icon: 'Motion', count: 0 },
      { id: 'framework-chart', name: '图表库', description: '', icon: 'BarChart3', count: 0 },
      { id: 'framework-state', name: '状态管理', description: '', icon: 'Database', count: 0 },
    ],
  },
  {
    id: 'design',
    name: '设计 & 素材',
    description: '设计工具、图标、配色、素材、原型等资源',
    icon: 'PenTool',
    count: 16,
    children: [
      { id: 'design-tool', name: '设计工具', description: '', icon: 'Edit3', count: 8 },
      { id: 'design-icon', name: '图标库', description: '', icon: 'Star', count: 0 },
      { id: 'design-color', name: '配色工具', description: '', icon: 'Droplets', count: 0 },
      { id: 'design-prototype', name: '原型设计', description: '', icon: 'FileText', count: 0 },
      { id: 'design-system', name: '设计系统', description: '', icon: 'Grid', count: 0 },
      { id: 'design-material', name: '素材资源', description: '', icon: 'Image', count: 0 },
      { id: 'assets-image', name: '图片资源', description: '', icon: 'Image', count: 2 },
      { id: 'assets-font', name: '字体资源', description: '', icon: 'Type', count: 2 },
      { id: 'assets-media', name: '音频视频', description: '', icon: 'Video', count: 2 },
      { id: 'assets-3d', name: '3D素材', description: '', icon: 'Box', count: 2 },
    ],
  },
  {
    id: 'backend',
    name: '后端 & 服务',
    description: 'Git平台、团队协作、API、数据库、测试、部署等',
    icon: 'Server',
    count: 20,
    children: [
      { id: 'collab-git', name: 'Git平台', description: '', icon: 'Github', count: 4 },
      { id: 'collab-team', name: '团队协作', description: '', icon: 'Users', count: 0 },
      { id: 'collab-review', name: '代码Review', description: '', icon: 'Eye', count: 0 },
      { id: 'collab-cicd', name: 'CI/CD', description: '', icon: 'Repeat', count: 0 },
      { id: 'collab-doc', name: '文档协作', description: '', icon: 'FileEdit', count: 0 },
      { id: 'api-debug', name: '接口调试', description: '', icon: 'Send', count: 2 },
      { id: 'api-mock', name: 'Mock服务', description: '', icon: 'Laugh', count: 2 },
      { id: 'api-db', name: '数据库', description: '', icon: 'Database', count: 2 },
      { id: 'api-cloud', name: '云服务', description: '', icon: 'Cloud', count: 2 },
      { id: 'test-unit', name: '单元测试', description: '', icon: 'TestTube', count: 2 },
      { id: 'test-e2e', name: 'E2E测试', description: '', icon: 'MousePointerClick', count: 2 },
      { id: 'test-deploy', name: '部署平台', description: '', icon: 'Rocket', count: 2 },
      { id: 'test-performance', name: '性能监控', description: '', icon: 'Gauge', count: 2 },
    ],
  },
  {
    id: 'learning',
    name: '学习 & 社区',
    description: '官方文档、教程、面试、社区、资讯等',
    icon: 'GraduationCap',
    count: 16,
    children: [
      { id: 'learning-doc', name: '官方文档', description: '', icon: 'BookOpen', count: 8 },
      { id: 'learning-tutorial', name: '视频教程', description: '', icon: 'PlayCircle', count: 0 },
      {
        id: 'learning-interview',
        name: '面试刷题',
        description: '',
        icon: 'CheckSquare',
        count: 0,
      },
      { id: 'learning-blog', name: '技术博客', description: '', icon: 'FileText', count: 0 },
      { id: 'learning-challenge', name: '编程挑战', description: '', icon: 'Award', count: 0 },
      { id: 'community-qa', name: '问答社区', description: '', icon: 'HelpCircle', count: 8 },
      { id: 'community-news', name: '资讯平台', description: '', icon: 'Newspaper', count: 0 },
      { id: 'community-job', name: '求职招聘', description: '', icon: 'Briefcase', count: 0 },
      { id: 'community-event', name: '开源活动', description: '', icon: 'Calendar', count: 0 },
    ],
  },
  {
    id: 'productivity',
    name: '效率工具',
    description: '笔记、项目管理、思维导图等',
    icon: 'Zap',
    count: 12,
    children: [
      { id: 'prod-note', name: '笔记工具', description: '', icon: 'StickyNote', count: 4 },
      { id: 'prod-project', name: '项目管理', description: '', icon: 'ListChecks', count: 8 },
      { id: 'prod-mindmap', name: '思维导图', description: '', icon: 'GitMerge', count: 0 },
      { id: 'prod-password', name: '密码管理', description: '', icon: 'Key', count: 0 },
      { id: 'prod-translate', name: '翻译工具', description: '', icon: 'Languages', count: 0 },
    ],
  },
]
