import type { RecommendedTool } from '../types/tool'

export const recommendedTools: RecommendedTool[] = [
  // 开发工具 - 代码编辑器
  {
    id: 'vscode',
    name: 'VS Code',
    description: '微软出品的免费开源代码编辑器，功能强大',
    icon: 'VsCode',
    svgIcon: `<svg t="1771912715589" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="8678" width="200" height="200"><path d="M0 0m184.32 0l655.36 0q184.32 0 184.32 184.32l0 655.36q0 184.32-184.32 184.32l-655.36 0q-184.32 0-184.32-184.32l0-655.36q0-184.32 184.32-184.32Z" fill="#FFFFFF" p-id="8679"></path><path d="M708.82304 161.9968l137.46176 67.24608c20.81792 10.62912 23.7056 18.28864 23.7056 29.29664l0.60416 506.23488c0 13.50656-7.30112 18.82112-27.42272 30.1568l-133.8368 67.08224c-5.5808 2.60096-10.04544 5.76512-43.47904 5.76512 0 0 28.93824 0.24576 28.93824-22.87616v-662.87616a25.15968 25.15968 0 0 0-24.13568-25.76384c29.6448 0 38.16448 5.7344 38.16448 5.7344z" fill="#4B9AE9" p-id="8680"></path><path d="M163.34848 613.02784a29.21472 29.21472 0 0 0 0 38.98368s35.11296 32.62464 45.4656 41.984 25.7024 5.12 35.64544-2.37568 450.29376-343.64416 450.29376-343.64416v-165.94944a25.06752 25.06752 0 0 0-24.13568-25.76384 18.11456 18.11456 0 0 0-12.3392 5.376z" fill="#2A63A4" p-id="8681"></path><path d="M208.92672 331.74528a23.17312 23.17312 0 0 1 32.45056 0l453.4272 343.61344v169.55392c0 23.25504-28.9792 22.8352-28.9792 22.8352a17.00864 17.00864 0 0 1-10.11712-5.53984l-495.77984-454.13376a22.31296 22.31296 0 0 1 0-31.54944z" fill="#3478C6" p-id="8682"></path></svg>`, 
    category: '代码开发',
    tags: ['编辑器', '开发工具', '微软'],
    url: 'https://code.visualstudio.com',
    stats: {
      stars: 152000,
      forks: 27000,
      usedBy: 14000000,
      version: '1.87.0',
      lastUpdated: '1周前',
    },
  },
  {
    id: 'webstorm',
    name: 'WebStorm',
    description: 'JetBrains出品的专业前端IDE，智能提示强大',
    icon: 'Code',
    svgIcon:
      `<svg t="1771906852776" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="6820" width="200" height="200"><path d="M0 107.2l137.6 817.6L704 1024 878.4 137.6 568 17.6l-150.4 80L256 1.6 0 107.2z" fill="#07C3F2" p-id="6821"></path><path d="M878.4 137.6L704 1024 137.6 924.8 878.4 137.6z" fill="#C793F3" p-id="6822"></path><path d="M878.4 137.6L137.6 924.8 0 107.2 256 1.6l161.6 96 150.4-80 310.4 120z" fill="#0793F3" p-id="6823"></path><path d="M941.28 144L281.6 355.2 652.8 0l238.4 20.8L941.28 144z" fill="#FCF84A" p-id="6824"></path><path d="M912 464l112 209.6L568 944l-187.2-129.6-99.2-459.2L941.28 144 1024 347.2 912 464z" fill="#0793F3" p-id="6825"></path><path d="M819.2 297.6L912 464l112-116.8L942.4 144l-123.2 153.6z" fill="#07C3F2" p-id="6826"></path><path d="M192 832h640V192H192v640z" p-id="6827"></path><path d="M566.88 504.48l35.2-42.24a123.84 123.84 0 0 0 80.96 32.8c24.32 0 39.04-9.6 39.04-25.44v-0.8c0-15.04-9.28-22.88-54.56-34.4-54.56-13.92-89.92-29.12-89.92-82.88 0-49.12 39.52-81.76 94.88-81.76a158.08 158.08 0 0 1 100.8 34.24l-31.04 44.96A128 128 0 0 0 672 321.6c-22.88 0-34.88 10.4-34.88 23.68v0.8c0 17.76 11.52 23.68 58.4 35.52 55.04 14.4 85.92 34.08 85.92 81.44 0 53.92-40.96 84-99.52 84a172.48 172.48 0 0 1-114.88-43.2M516.32 272l-39.52 154.88L431.52 272h-44.96l-45.28 154.88L301.92 272H240l75.84 272h49.76l43.52-153.6 42.88 153.6h50.4l75.68-272h-61.76zM256 752h240v-40H256V752z" fill="#FFFFFF" p-id="6828"></path></svg>`,
    category: '代码开发',
    tags: ['IDE', 'JetBrains', '专业开发'],
    url: 'https://www.jetbrains.com/webstorm',
    stats: {
      stars: 0,
      forks: 0,
      usedBy: 3200000,
      version: '2024.1',
      lastUpdated: '2周前',
    },
  },
  {
    id: 'sublime',
    name: 'Sublime Text',
    description: '轻量级代码编辑器，启动速度快，扩展性强',
    icon: 'FileCode',
    svgIcon:  `
    <svg t="1771912791999" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="11366" width="200" height="200"><path d="M906.06864 514.706791c0-12.023184-8.587989-18.893575-19.466108-15.45838L137.157383 736.849433c-10.878119 3.435195-19.466108 16.030912-19.466108 28.054096V1007.657344c0 12.023184 8.587989 18.893575 19.466108 15.458379l748.872617-237.601021c10.878119-3.435195 19.466108-16.030912 19.466108-28.054096V514.706791z" p-id="11367" fill="#fb780e"></path><path d="M117.691275 507.263867c0 12.023184 8.587989 24.618901 19.466108 28.054097L886.03 772.918985c10.878119 3.435195 19.466108-3.435195 19.466108-15.458379V514.706791c0-12.023184-8.587989-24.618901-19.466108-28.054097L137.157383 249.051673c-10.878119-3.435195-19.466108 3.435195-19.466108 15.45838v242.753814z" p-id="11368" fill="#fb780e"></path><path d="M906.06864 16.603445c0-12.023184-8.587989-18.893575-19.466108-15.45838L137.157383 238.173554c-10.878119 3.435195-19.466108 16.030912-19.466108 28.054096v242.753815c0 12.023184 8.587989 18.893575 19.466108 15.45838l748.872617-237.601022c10.878119-3.435195 19.466108-16.030912 19.466108-28.054096 0.572533 0 0.572533-242.181282 0.572532-242.181282z" p-id="11369" fill="#fb780e"></path></svg>
    `,
    category: '代码开发',
    tags: ['编辑器', '轻量', '高性能'],
    url: 'https://www.sublimetext.com',
    stats: {
      stars: 15000,
      forks: 1800,
      usedBy: 8500000,
      version: '4.0',
      lastUpdated: '2个月前',
    },
  },
  {
    id: 'atom',
    name: 'Atom',
    description: 'GitHub出品的开源代码编辑器，高度可定制',
    icon: 'Atom',
    svgIcon:
      '<svg t="1771908345678" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" width="200" height="200"><path d="M512 0C229.2 0 0 229.2 0 512s229.2 512 512 512 512-229.2 512-512S794.8 0 512 0z m289.3 704.4c-10.1 10.1-21.1 19.3-32.8 27.6-21.4 15.2-44.8 27.6-69.7 36.8-19.2 7.1-39.2 12.3-59.8 15.5-12.5 1.9-25.1 2.9-37.8 2.9-8.7 0-17.5-0.3-26.2-0.9-27.2-1.9-54.1-8.6-79.7-19.7-24.8-10.8-48.2-24.9-69.4-41.7-8.4-6.7-16.4-13.8-24-21.4-7.6-7.6-14.7-15.6-21.4-24-16.8-21.2-30.9-44.6-41.7-69.4-11.1-25.6-17.8-52.5-19.7-79.7-0.6-8.7-0.9-17.5-0.9-26.2 0-12.7 1-25.3 2.9-37.8 3.2-20.6 8.4-40.6 15.5-59.8 9.2-24.9 21.6-48.3 36.8-69.7 8.3-11.7 17.5-22.7 27.6-32.8 10.1-10.1 21.1-19.3 32.8-27.6 21.4-15.2 44.8-27.6 69.7-36.8 19.2-7.1 39.2-12.3 59.8-15.5 12.5-1.9 25.1-2.9 37.8-2.9 8.7 0 17.5 0.3 26.2 0.9 27.2 1.9 54.1 8.6 79.7 19.7 24.8 10.8 48.2 24.9 69.4 41.7 8.4 6.7 16.4 13.8 24 21.4 7.6 7.6 14.7 15.6 21.4 24 16.8 21.2 30.9 44.6 41.7 69.4 11.1 25.6 17.8 52.5 19.7 79.7 0.6 8.7 0.9 17.5 0.9 26.2 0 12.7-1 25.3-2.9 37.8-3.2 20.6-8.4 40.6-15.5 59.8-9.2 24.9-21.6 48.3-36.8 69.7-8.3 11.7-17.5 22.7-27.6 32.8z" fill="#5FB57D" p-id="3456"></path><path d="M671.4 590.1c-6.7 18.6-16.6 35.8-29.1 51.3-12.5 15.5-27.4 29.2-44.3 40.5-16.9 11.3-35.6 20.1-55.5 25.9-19.9 5.8-40.7 8.6-61.7 8.2v-255.9c21 0.4 41.8 2.3 61.7 8.2 19.9 5.8 38.6 14.6 55.5 25.9 16.9 11.3 31.8 25 44.3 40.5 12.5 15.5 22.4 32.7 29.1 51.3 6.7 18.6 10 38 10 57.6s-3.3 39-10 57.6z" fill="#40A977" p-id="3457"></path></svg>',
    category: '代码开发',
    tags: ['编辑器', '开源', 'GitHub'],
    url: 'https://atom.io',
    stats: {
      stars: 59800,
      forks: 18500,
      usedBy: 2300000,
      version: '1.63.0',
      lastUpdated: '2年前',
    },
  },

  // 开发工具 - 在线运行环境
  {
    id: 'codepen',
    name: 'CodePen',
    description: '前端代码在线演示和分享平台，创意代码社区',
    icon: 'CodePen',
    svgIcon: ``,
    category: '开发工具',
    tags: ['代码演示', '在线运行', '前端社区'],
    url: 'https://codepen.io',
  },
  {
    id: 'stackblitz',
    name: 'StackBlitz',
    description: '在线IDE，支持React/Vue/Angular等框架实时运行',
    icon: 'Zap',
    svgIcon: ``,
    category: '开发工具',
    tags: ['在线IDE', '实时运行', '开源'],
    url: 'https://stackblitz.com',
  },
  {
    id: 'codesandbox',
    name: 'CodeSandbox',
    description: '在线代码沙箱，前端项目快速原型验证',
    icon: 'Box',
    svgIcon: ``,
    category: '开发工具',
    tags: ['在线IDE', '沙箱', '原型'],
    url: 'https://codesandbox.io',
  },
  {
    id: 'jsfiddle',
    name: 'JSFiddle',
    description: '经典的在线代码编辑器，支持HTML/CSS/JS预览',
    icon: 'Music',
    svgIcon: ``,
    category: '开发工具',
    tags: ['在线编辑器', '代码预览', '经典'],
    url: 'https://jsfiddle.net',
  },

  // 前端框架 - 主流框架
  {
    id: 'react',
    name: 'React 官方文档',
    description: 'React 官方中文文档，学习React首选资源',
    icon: 'React',
    svgIcon: ``,
    category: '前端框架',
    tags: ['React', '前端框架', '文档'],
    url: 'https://react.dev',
  },
  {
    id: 'vue',
    name: 'Vue 官方文档',
    description: 'Vue.js 官方中文文档，渐进式JavaScript框架',
    icon: 'Vue',
    svgIcon: ``,
    category: '前端框架',
    tags: ['Vue', '前端框架', '文档'],
    url: 'https://cn.vuejs.org',
  },
  {
    id: 'angular',
    name: 'Angular 官网',
    description: 'Angular 官方网站，Google 出品的前端框架',
    icon: 'Angular',
    svgIcon: ``,
    category: '前端框架',
    tags: ['Angular', '前端框架', 'Google'],
    url: 'https://angular.io',
  },
  {
    id: 'svelte',
    name: 'Svelte 官网',
    description: '新一代前端框架，编译时框架，高性能',
    icon: 'Flame',
    svgIcon: ``,
    category: '前端框架',
    tags: ['Svelte', '前端框架', '编译型'],
    url: 'https://svelte.dev',
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    description: 'React 服务端渲染框架，全栈开发首选',
    icon: 'Server',
    svgIcon: ``,
    category: '前端框架',
    tags: ['React', 'SSR', '全栈'],
    url: 'https://nextjs.org',
  },
  {
    id: 'nuxt',
    name: 'Nuxt.js',
    description: 'Vue.js 服务端渲染框架，开发体验优秀',
    icon: 'Server',
    svgIcon: ``,
    category: '前端框架',
    tags: ['Vue', 'SSR', '全栈'],
    url: 'https://nuxt.com',
  },
  {
    id: 'nestjs',
    name: 'NestJS',
    description: 'Node.js 企业级后端框架，TypeScript 友好',
    icon: 'Hexagon',
    svgIcon: ``,
    category: '前端框架',
    tags: ['Node.js', '后端', 'TypeScript'],
    url: 'https://nestjs.com',
  },
  {
    id: 'express',
    name: 'Express',
    description: 'Node.js 轻量级Web框架，使用最广泛',
    icon: 'Globe',
    svgIcon: ``,
    category: '前端框架',
    tags: ['Node.js', 'Web框架', '轻量'],
    url: 'https://expressjs.com',
  },

  // UI设计 - 设计工具
  {
    id: 'figma',
    name: 'Figma',
    description: '在线UI设计协作工具，团队协作必备',
    icon: 'Figma',
    svgIcon: ``,
    category: 'UI设计',
    tags: ['设计', 'UI', '协作'],
    url: 'https://www.figma.com',
  },
  {
    id: 'sketch',
    name: 'Sketch',
    description: '专业的UI设计工具，Mac平台首选',
    icon: 'PenTool',
    svgIcon: ``,
    category: 'UI设计',
    tags: ['UI设计', 'Mac', '原型设计'],
    url: 'https://www.sketch.com',
  },
  {
    id: 'adobexd',
    name: 'Adobe XD',
    description: 'Adobe出品的UI/UX设计工具，无缝集成Creative Cloud',
    icon: 'PenTool',
    svgIcon: ``,
    category: 'UI设计',
    tags: ['Adobe', 'UI设计', '原型'],
    url: 'https://www.adobe.com/products/xd.html',
  },
  {
    id: 'canva',
    name: 'Canva',
    description: '在线平面设计工具，海量模板资源',
    icon: 'Image',
    svgIcon: ``,
    category: 'UI设计',
    tags: ['平面设计', '模板', '图片处理'],
    url: 'https://www.canva.cn',
  },
  {
    id: 'figjam',
    name: 'FigJam',
    description: 'Figma 出品的在线白板工具，团队协作头脑风暴',
    icon: 'Square',
    svgIcon: ``,
    category: 'UI设计',
    tags: ['白板', '协作', '头脑风暴'],
    url: 'https://www.figma.com/figjam',
  },
  {
    id: 'miro',
    name: 'Miro',
    description: '在线协作白板，支持多种团队协作场景',
    icon: 'Layout',
    svgIcon: ``,
    category: 'UI设计',
    tags: ['白板', '协作', '团队'],
    url: 'https://miro.com',
  },
  {
    id: 'zeplin',
    name: 'Zeplin',
    description: '设计稿标注和切图工具，设计师和开发者协作神器',
    icon: 'Share2',
    svgIcon: ``,
    category: 'UI设计',
    tags: ['标注', '切图', '协作'],
    url: 'https://zeplin.io',
  },
  {
    id: 'lanhu',
    name: '蓝湖',
    description: '国内的产品设计协作平台，设计稿管理标注',
    icon: 'Droplet',
    svgIcon: ``,
    category: 'UI设计',
    tags: ['国内', '设计协作', '标注'],
    url: 'https://lanhuapp.com',
  },

  // 代码托管 - Git平台
  {
    id: 'github',
    name: 'GitHub',
    description: '全球最大的开源代码托管平台，开发者必备',
    icon: 'Github',
    svgIcon: ``,
    category: '代码托管',
    tags: ['Git', '开源', '代码托管'],
    url: 'https://github.com',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    description: '开源代码托管平台，支持完整DevOps生命周期',
    icon: 'GitBranch',
    svgIcon: ``,
    category: '代码托管',
    tags: ['Git', '开源', 'DevOps'],
    url: 'https://gitlab.com',
  },
  {
    id: 'gitee',
    name: 'Gitee',
    description: '国内的代码托管平台，访问速度快',
    icon: 'GitBranch',
    svgIcon: ``,
    category: '代码托管',
    tags: ['Git', '国内', '代码托管'],
    url: 'https://gitee.com',
  },
  {
    id: 'bitbucket',
    name: 'Bitbucket',
    description: 'Atlassian出品的代码托管平台，适合团队使用',
    icon: 'GitMerge',
    svgIcon: ``,
    category: '代码托管',
    tags: ['Git', '团队协作', 'Atlassian'],
    url: 'https://bitbucket.org',
  },

  // 学习资源 - 官方文档
  {
    id: 'mdn',
    name: 'MDN Web Docs',
    description: 'Mozilla 开发者网络，最权威的Web开发文档',
    icon: 'BookOpen',
    svgIcon: ``,
    category: '学习资源',
    tags: ['Web', '文档', '前端'],
    url: 'https://developer.mozilla.org',
  },
  {
    id: 'typescript',
    name: 'TypeScript 官网',
    description: 'TypeScript 官方网站，JavaScript的超集',
    icon: 'Code',
    svgIcon: ``,
    category: '学习资源',
    tags: ['TypeScript', '类型系统', 'JavaScript'],
    url: 'https://www.typescriptlang.org',
  },
  {
    id: 'nodejs',
    name: 'Node.js 官网',
    description: 'Node.js 官方文档，JavaScript运行时',
    icon: 'Server',
    svgIcon: ``,
    category: '学习资源',
    tags: ['Node.js', '后端', 'JavaScript'],
    url: 'https://nodejs.org',
  },
  {
    id: 'w3school',
    name: 'W3School',
    description: '中文Web开发教程，入门级学习首选',
    icon: 'GraduationCap',
    svgIcon: ``,
    category: '学习资源',
    tags: ['教程', '入门', '中文'],
    url: 'https://www.w3school.com.cn',
  },
  {
    id: 'es6',
    name: 'ES6 入门教程',
    description: '阮一峰的ES6入门教程，系统学习JavaScript新特性',
    icon: 'BookOpen',
    svgIcon: ``,
    category: '学习资源',
    tags: ['JavaScript', 'ES6', '教程'],
    url: 'https://es6.ruanyifeng.com',
  },
  {
    id: 'javascript-info',
    name: '现代 JavaScript 教程',
    description: '全面深入的JavaScript教程，从基础到高级',
    icon: 'BookOpen',
    svgIcon: ``,
    category: '学习资源',
    tags: ['JavaScript', '教程', '深入'],
    url: 'https://zh.javascript.info',
  },
  {
    id: 'leetcode',
    name: 'LeetCode',
    description: '算法刷题平台，面试准备必备',
    icon: 'Code',
    svgIcon: ``,
    category: '学习资源',
    tags: ['算法', '面试', '刷题'],
    url: 'https://leetcode.cn',
  },
  {
    id: 'freecodecamp',
    name: 'freeCodeCamp',
    description: '免费编程学习平台，实战项目驱动',
    icon: 'Code',
    svgIcon: ``,
    category: '学习资源',
    tags: ['免费', '实战', '编程学习'],
    url: 'https://www.freecodecamp.org',
  },

  // 效率工具 - 笔记工具
  {
    id: 'notion',
    name: 'Notion',
    description: '全能笔记和知识管理工具，支持团队协作',
    icon: 'BookOpen',
    svgIcon: ``,
    category: '效率工具',
    tags: ['笔记', '知识管理', '协作'],
    url: 'https://www.notion.so',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    description: '本地优先的双向链接笔记工具，适合知识管理',
    icon: 'Gem',
    svgIcon: ``,
    category: '效率工具',
    tags: ['笔记', '本地', '双向链接'],
    url: 'https://obsidian.md',
  },
  {
    id: 'yuque',
    name: '语雀',
    description: '蚂蚁集团出品的知识管理平台，中文友好',
    icon: 'FileText',
    svgIcon: ``,
    category: '效率工具',
    tags: ['笔记', '知识管理', '国内'],
    url: 'https://www.yuque.com',
  },
  {
    id: 'notion-cn',
    name: 'Notion 中文站',
    description: 'Notion 国内版本，访问速度快',
    icon: 'BookOpen',
    svgIcon: ``,
    category: '效率工具',
    tags: ['笔记', '国内', '协作'],
    url: 'https://notion.so',
  },

  // 效率工具 - 项目管理
  {
    id: 'trello',
    name: 'Trello',
    description: '看板式项目管理工具，简单易用',
    icon: 'List',
    svgIcon: ``,
    category: '效率工具',
    tags: ['项目管理', '看板', '协作'],
    url: 'https://trello.com',
  },
  {
    id: 'jira',
    name: 'Jira',
    description: '专业的项目管理和问题跟踪工具，企业级',
    icon: 'ListChecks',
    svgIcon: ``,
    category: '效率工具',
    tags: ['项目管理', '敏捷开发', '企业级'],
    url: 'https://www.atlassian.com/software/jira',
  },
  {
    id: 'asana',
    name: 'Asana',
    description: '团队任务管理工具，提升协作效率',
    icon: 'CheckSquare',
    svgIcon: ``,
    category: '效率工具',
    tags: ['任务管理', '团队协作', '项目管理'],
    url: 'https://asana.com',
  },
  {
    id: 'notion-project',
    name: 'Notion 项目管理',
    description: 'Notion 强大的数据库功能，灵活定制项目管理',
    icon: 'Database',
    svgIcon: ``,
    category: '效率工具',
    tags: ['项目管理', '自定义', 'Notion'],
    url: 'https://www.notion.so',
  },
  {
    id: 'feishu',
    name: '飞书',
    description: '字节跳动出品的企业协作平台，文档/会议/项目管理一体',
    icon: 'Users',
    svgIcon: ``,
    category: '效率工具',
    tags: ['企业协作', '国内', '字节跳动'],
    url: 'https://www.feishu.cn',
  },
  {
    id: 'dingtalk',
    name: '钉钉',
    description: '阿里巴巴出品的企业办公平台，国内企业广泛使用',
    icon: 'MessageSquare',
    svgIcon: ``,
    category: '效率工具',
    tags: ['企业办公', '国内', '阿里巴巴'],
    url: 'https://www.dingtalk.com',
  },
  {
    id: 'wechat-work',
    name: '企业微信',
    description: '腾讯出品的企业沟通和协作工具，和微信打通',
    icon: 'MessageCircle',
    svgIcon: ``,
    category: '效率工具',
    tags: ['企业协作', '国内', '腾讯'],
    url: 'https://work.weixin.qq.com',
  },
  {
    id: 'slack',
    name: 'Slack',
    description: '团队沟通工具，集成丰富的第三方服务',
    icon: 'MessageSquare',
    svgIcon: ``,
    category: '效率工具',
    tags: ['团队沟通', '集成', '协作'],
    url: 'https://slack.com',
  },

  // 社区平台 - 问答社区
  {
    id: 'stackoverflow',
    name: 'Stack Overflow',
    description: '程序员问答社区，解决技术问题首选',
    icon: 'HelpCircle',
    svgIcon: ``,
    category: '社区平台',
    tags: ['问答', '技术社区', '程序员'],
    url: 'https://stackoverflow.com',
  },
  {
    id: 'segmentfault',
    name: '思否',
    description: '国内的技术问答社区，开发者交流平台',
    icon: 'MessageSquare',
    svgIcon: ``,
    category: '社区平台',
    tags: ['问答', '国内', '技术社区'],
    url: 'https://segmentfault.com',
  },
  {
    id: 'zhihu',
    name: '知乎',
    description: '中文问答社区，技术问题讨论活跃',
    icon: 'FileText',
    category: '社区平台',
    tags: ['问答', '知识分享', '中文社区'],
    url: 'https://www.zhihu.com',
  },
  {
    id: 'v2ex',
    name: 'V2EX',
    description: '程序员社区，技术分享和讨论平台',
    icon: 'MessageSquare',
    category: '社区平台',
    tags: ['技术社区', '程序员', '分享'],
    url: 'https://www.v2ex.com',
  },
  {
    id: 'juejin',
    name: '掘金',
    description: '国内的开发者社区，技术文章和资讯分享',
    icon: 'Gem',
    category: '社区平台',
    tags: ['技术社区', '国内', '文章分享'],
    url: 'https://juejin.cn',
  },
  {
    id: 'devto',
    name: 'Dev.to',
    description: '国际开发者社区，技术文章分享平台',
    icon: 'Code',
    category: '社区平台',
    tags: ['技术社区', '国际', '文章分享'],
    url: 'https://dev.to',
  },
  {
    id: 'medium',
    name: 'Medium',
    description: '优质内容平台，技术深度文章众多',
    icon: 'FileText',
    category: '社区平台',
    tags: ['内容平台', '深度文章', '国际'],
    url: 'https://medium.com',
  },
  {
    id: 'hackernews',
    name: 'Hacker News',
    description: 'Y Combinator 旗下的科技新闻和讨论平台',
    icon: 'Newspaper',
    category: '社区平台',
    tags: ['科技新闻', '讨论', '国际'],
    url: 'https://news.ycombinator.com',
  },

  // API & 数据服务 - 接口调试
  {
    id: 'postman',
    name: 'Postman',
    description: '最流行的API接口调试工具，功能全面',
    icon: 'Send',
    category: 'API工具',
    tags: ['接口调试', 'API', '测试'],
    url: 'https://www.postman.com',
  },
  {
    id: 'apifox',
    name: 'Apifox',
    description: '国内一站式API协作平台，接口调试/文档/Mock一体化',
    icon: 'Send',
    category: 'API工具',
    tags: ['接口调试', 'API', '国内'],
    url: 'https://www.apifox.cn',
  },

  // API & 数据服务 - Mock服务
  {
    id: 'mockjs',
    name: 'Mock.js',
    description: '生成随机模拟数据的工具，前端开发必备',
    icon: 'Laugh',
    category: '数据服务',
    tags: ['Mock', '模拟数据', '前端工具'],
    url: 'http://mockjs.com',
  },
  {
    id: 'jsonplaceholder',
    name: 'JSONPlaceholder',
    description: '免费的在线REST API Mock服务',
    icon: 'Database',
    category: '数据服务',
    tags: ['Mock', 'REST API', '免费'],
    url: 'https://jsonplaceholder.typicode.com',
  },

  // API & 数据服务 - 数据库
  {
    id: 'mongodb',
    name: 'MongoDB',
    description: '最流行的NoSQL文档型数据库',
    icon: 'Database',
    category: '数据服务',
    tags: ['数据库', 'NoSQL', '文档型'],
    url: 'https://www.mongodb.com',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    description: '开源的Firebase替代方案，后端即服务',
    icon: 'Server',
    category: '数据服务',
    tags: ['BaaS', '数据库', '开源'],
    url: 'https://supabase.com',
  },

  // API & 数据服务 - 云服务
  {
    id: 'vercel',
    name: 'Vercel',
    description: '前端项目部署平台，Next.js官方推荐',
    icon: 'Cloud',
    category: '数据服务',
    tags: ['云服务', '部署', '前端'],
    url: 'https://vercel.com',
  },
  {
    id: 'netlify',
    name: 'Netlify',
    description: '静态网站和前端应用部署平台',
    icon: 'Cloud',
    category: '数据服务',
    tags: ['云服务', '部署', '静态网站'],
    url: 'https://www.netlify.com',
  },

  // 浏览器 & 插件 - 主流浏览器
  {
    id: 'chrome',
    name: 'Google Chrome',
    description: '市场占有率最高的浏览器，开发者友好',
    icon: 'Globe',
    category: '浏览器',
    tags: ['浏览器', 'Google', '开发者工具'],
    url: 'https://www.google.com/chrome',
  },
  {
    id: 'edge',
    name: 'Microsoft Edge',
    description: '微软基于Chromium开发的浏览器，性能优秀',
    icon: 'Globe',
    category: '浏览器',
    tags: ['浏览器', '微软', 'Chromium'],
    url: 'https://www.microsoft.com/edge',
  },

  // 浏览器 & 插件 - 开发插件
  {
    id: 'react-devtools',
    name: 'React DevTools',
    description: 'React官方开发调试插件',
    icon: 'Code',
    category: '开发插件',
    tags: ['React', '调试', '浏览器插件'],
    url: 'https://react.dev/learn/react-developer-tools',
  },
  {
    id: 'vue-devtools',
    name: 'Vue DevTools',
    description: 'Vue.js官方开发调试插件',
    icon: 'Code',
    category: '开发插件',
    tags: ['Vue', '调试', '浏览器插件'],
    url: 'https://devtools.vuejs.org',
  },

  // 浏览器 & 插件 - 性能分析
  {
    id: 'lighthouse',
    name: 'Lighthouse',
    description: 'Google官方网页性能分析工具',
    icon: 'Activity',
    category: '开发插件',
    tags: ['性能分析', '最佳实践', 'SEO'],
    url: 'https://developer.chrome.com/docs/lighthouse/overview',
  },
  {
    id: 'web-vitals',
    name: 'Web Vitals',
    description: 'Google官方网页核心性能指标监控工具',
    icon: 'Gauge',
    category: '开发插件',
    tags: ['性能监控', '用户体验', '指标'],
    url: 'https://web.dev/vitals',
  },

  // 浏览器 & 插件 - 抓包工具
  {
    id: 'charles',
    name: 'Charles',
    description: '常用的HTTP代理/抓包工具',
    icon: 'Network',
    category: '开发插件',
    tags: ['抓包', '代理', 'HTTP'],
    url: 'https://www.charlesproxy.com',
  },
  {
    id: 'fiddler',
    name: 'Fiddler',
    description: '功能强大的Web调试代理工具',
    icon: 'Network',
    category: '开发插件',
    tags: ['抓包', '调试', '代理'],
    url: 'https://www.telerik.com/fiddler',
  },

  // 素材资源 - 图片资源
  {
    id: 'unsplash',
    name: 'Unsplash',
    description: '免费高质量可商用图片资源库',
    icon: 'Image',
    category: '素材资源',
    tags: ['图片', '免费', '商用'],
    url: 'https://unsplash.com',
  },
  {
    id: 'pexels',
    name: 'Pexels',
    description: '免费的高质量图片和视频素材库',
    icon: 'Image',
    category: '素材资源',
    tags: ['图片', '视频', '免费'],
    url: 'https://www.pexels.com',
  },

  // 素材资源 - 字体资源
  {
    id: 'google-fonts',
    name: 'Google Fonts',
    description: 'Google免费开源字体库，支持中文',
    icon: 'Type',
    category: '素材资源',
    tags: ['字体', '免费', '开源'],
    url: 'https://fonts.google.com',
  },
  {
    id: 'font-awesome',
    name: 'Font Awesome',
    description: '最流行的图标字体库，图标丰富',
    icon: 'Star',
    category: '素材资源',
    tags: ['图标', '字体', '开源'],
    url: 'https://fontawesome.com',
  },

  // 素材资源 - 音频视频
  {
    id: 'mixkit',
    name: 'Mixkit',
    description: '免费可商用的视频、音乐、音效素材',
    icon: 'Video',
    category: '素材资源',
    tags: ['视频', '音频', '免费'],
    url: 'https://mixkit.co',
  },
  {
    id: 'soundbible',
    name: 'SoundBible',
    description: '免费音效和声音片段资源库',
    icon: 'Volume2',
    category: '素材资源',
    tags: ['音效', '音频', '免费'],
    url: 'https://soundbible.com',
  },

  // 素材资源 - 3D素材
  {
    id: 'sketchfab',
    name: 'Sketchfab',
    description: '3D模型分享和发布平台，大量免费资源',
    icon: 'Box',
    category: '素材资源',
    tags: ['3D模型', '分享', '免费'],
    url: 'https://sketchfab.com',
  },
  {
    id: 'threejs',
    name: 'Three.js',
    description: '最流行的WebGL 3D开发框架',
    icon: 'Cube',
    category: '素材资源',
    tags: ['3D', 'WebGL', '框架'],
    url: 'https://threejs.org',
  },

  // 测试 & 部署 - 单元测试
  {
    id: 'jest',
    name: 'Jest',
    description: 'Facebook出品的JavaScript单元测试框架',
    icon: 'TestTube',
    category: '测试工具',
    tags: ['单元测试', 'JavaScript', 'Facebook'],
    url: 'https://jestjs.io',
  },
  {
    id: 'vitest',
    name: 'Vitest',
    description: '基于Vite的下一代前端测试框架，速度极快',
    icon: 'TestTube',
    category: '测试工具',
    tags: ['单元测试', 'Vite', '高性能'],
    url: 'https://vitest.dev',
  },

  // 测试 & 部署 - E2E测试
  {
    id: 'cypress',
    name: 'Cypress',
    description: '现代化的前端E2E测试工具，简单易用',
    icon: 'MousePointerClick',
    category: '测试工具',
    tags: ['E2E测试', '前端', '自动化'],
    url: 'https://www.cypress.io',
  },
  {
    id: 'playwright',
    name: 'Playwright',
    description: '微软出品的跨浏览器自动化测试工具',
    icon: 'MousePointerClick',
    category: '测试工具',
    tags: ['E2E测试', '自动化', '微软'],
    url: 'https://playwright.dev',
  },

  // 测试 & 部署 - 部署平台
  {
    id: 'github-pages',
    name: 'GitHub Pages',
    description: 'GitHub提供的免费静态网站托管服务',
    icon: 'Rocket',
    category: '部署平台',
    tags: ['部署', '静态网站', '免费'],
    url: 'https://pages.github.com',
  },
  {
    id: 'cloudflare-pages',
    name: 'Cloudflare Pages',
    description: 'Cloudflare提供的全球CDN加速静态网站部署',
    icon: 'Rocket',
    category: '部署平台',
    tags: ['部署', 'CDN', '全球加速'],
    url: 'https://pages.cloudflare.com',
  },

  // 测试 & 部署 - 性能监控
  {
    id: 'sentry',
    name: 'Sentry',
    description: '应用错误和性能监控平台，实时报警',
    icon: 'Activity',
    category: '测试工具',
    tags: ['错误监控', '性能', '实时'],
    url: 'https://sentry.io',
  },
  {
    id: 'datadog',
    name: 'Datadog',
    description: '全栈性能监控和安全平台，企业级',
    icon: 'Gauge',
    category: '测试工具',
    tags: ['性能监控', '企业级', '可观测性'],
    url: 'https://www.datadoghq.com',
  },

  // 开发工具 - 调试工具
  {
    id: 'eruda',
    name: 'Eruda',
    description: '手机端网页调试工具，H5开发必备',
    icon: 'Bug',
    category: '开发工具',
    tags: ['调试', '移动端', '前端工具'],
    url: 'https://eruda.liriliri.io',
  },
  {
    id: 'whistle',
    name: 'Whistle',
    description: '跨平台web调试代理工具，功能强大',
    icon: 'Bug',
    category: '开发工具',
    tags: ['调试', '代理', '抓包'],
    url: 'https://wproxy.org/whistle',
  },

  // 开发工具 - 代码格式化
  {
    id: 'prettier',
    name: 'Prettier',
    description: '最流行的代码格式化工具，支持多语言',
    icon: 'AlignLeft',
    category: '开发工具',
    tags: ['格式化', '代码规范', '前端工具'],
    url: 'https://prettier.io',
  },
  {
    id: 'eslint',
    name: 'ESLint',
    description: 'JavaScript代码质量检测工具',
    icon: 'AlignLeft',
    category: '开发工具',
    tags: ['格式化', '代码规范', '静态检查'],
    url: 'https://eslint.org',
  },

  // 开发工具 - 编译构建
  {
    id: 'vite',
    name: 'Vite',
    description: '下一代前端构建工具，速度极快',
    icon: 'Hammer',
    category: '开发工具',
    tags: ['构建', '前端', '高性能'],
    url: 'https://vitejs.dev',
  },
  {
    id: 'webpack',
    name: 'Webpack',
    description: '最流行的前端模块打包工具',
    icon: 'Hammer',
    category: '开发工具',
    tags: ['构建', '打包', '模块化'],
    url: 'https://webpack.js.org',
  },

  // 开发工具 - 包管理工具
  {
    id: 'pnpm',
    name: 'pnpm',
    description: '速度快、节省磁盘空间的包管理器',
    icon: 'Package',
    category: '开发工具',
    tags: ['包管理', 'npm', '高性能'],
    url: 'https://pnpm.io',
  },
  {
    id: 'yarn',
    name: 'Yarn',
    description: 'Facebook出品的npm替代包管理器',
    icon: 'Package',
    category: '开发工具',
    tags: ['包管理', 'npm', 'Facebook'],
    url: 'https://yarnpkg.com',
  },

  // 前端框架 & 库 - UI组件库
  {
    id: 'antd',
    name: 'Ant Design',
    description: '蚂蚁集团出品的企业级UI设计语言',
    icon: 'Palette',
    category: '框架库',
    tags: ['UI组件', 'React', '企业级'],
    url: 'https://ant.design',
  },
  {
    id: 'element-ui',
    name: 'Element UI',
    description: '饿了么出品的Vue2组件库',
    icon: 'Palette',
    category: '框架库',
    tags: ['UI组件', 'Vue', '前端'],
    url: 'https://element.eleme.io',
  },

  // 前端框架 & 库 - 工具函数库
  {
    id: 'lodash',
    name: 'Lodash',
    description: '一致性、模块化、高性能的JavaScript实用工具库',
    icon: 'FunctionSquare',
    category: '框架库',
    tags: ['工具函数', 'JavaScript', '实用工具'],
    url: 'https://lodash.com',
  },
  {
    id: 'ramda',
    name: 'Ramda',
    description: '函数式编程风格的JavaScript工具库',
    icon: 'FunctionSquare',
    category: '框架库',
    tags: ['工具函数', '函数式编程', 'JavaScript'],
    url: 'https://ramdajs.com',
  },

  // 前端框架 & 库 - 动画库
  {
    id: 'framer-motion',
    name: 'Framer Motion',
    description: 'React开源动画库，简单易用',
    icon: 'Motion',
    category: '框架库',
    tags: ['动画', 'React', '开源'],
    url: 'https://www.framer.com/motion',
  },
  {
    id: 'gsap',
    name: 'GSAP',
    description: '专业级Web动画库，性能强大',
    icon: 'Motion',
    category: '框架库',
    tags: ['动画', '高性能', '专业级'],
    url: 'https://greensock.com/gsap',
  },

  // 前端框架 & 库 - 图表库
  {
    id: 'echarts',
    name: 'ECharts',
    description: '百度开源的强大的数据可视化图表库',
    icon: 'BarChart3',
    category: '框架库',
    tags: ['图表', '数据可视化', '开源'],
    url: 'https://echarts.apache.org',
  },
  {
    id: 'chartjs',
    name: 'Chart.js',
    description: '简单灵活的JavaScript图表库',
    icon: 'BarChart3',
    category: '框架库',
    tags: ['图表', '轻量', '易用'],
    url: 'https://www.chartjs.org',
  },

  // 前端框架 & 库 - 状态管理
  {
    id: 'redux',
    name: 'Redux',
    description: 'JavaScript状态容器，提供可预测的状态管理',
    icon: 'Database',
    category: '框架库',
    tags: ['状态管理', 'React', 'JavaScript'],
    url: 'https://redux.js.org',
  },
  {
    id: 'zustand',
    name: 'Zustand',
    description: '轻量、灵活的React状态管理库',
    icon: 'Database',
    category: '框架库',
    tags: ['状态管理', 'React', '轻量'],
    url: 'https://zustand-demo.pmnd.rs',
  },

  // UI/UX设计 - 图标库
  {
    id: 'iconfont',
    name: 'Iconfont',
    description: '阿里妈妈出品的矢量图标管理平台',
    icon: 'Star',
    category: '设计资源',
    tags: ['图标', '免费', '阿里'],
    url: 'https://www.iconfont.cn',
  },
  {
    id: 'heroicons',
    name: 'Heroicons',
    description: 'Tailwind官方出品的精美SVG图标库',
    icon: 'Star',
    category: '设计资源',
    tags: ['图标', 'SVG', 'Tailwind'],
    url: 'https://heroicons.com',
  },

  // UI/UX设计 - 配色工具
  {
    id: 'coolors',
    name: 'Coolors',
    description: '快速生成漂亮配色方案的工具',
    icon: 'Droplets',
    category: '设计资源',
    tags: ['配色', '设计工具', '免费'],
    url: 'https://coolors.co',
  },
  {
    id: 'colorhunt',
    name: 'Color Hunt',
    description: '设计师分享的精美配色方案集合',
    icon: 'Droplets',
    category: '设计资源',
    tags: ['配色', '设计灵感', '免费'],
    url: 'https://colorhunt.co',
  },

  // UI/UX设计 - 原型设计
  {
    id: 'axure',
    name: 'Axure RP',
    description: '专业的快速原型设计工具',
    icon: 'FileText',
    category: '设计资源',
    tags: ['原型', '交互设计', '专业级'],
    url: 'https://www.axure.com',
  },
  {
    id: 'mockingbot',
    name: '墨刀 MockingBot',
    description: '国内领先的移动应用原型和协作设计平台',
    icon: 'FileText',
    category: '设计资源',
    tags: ['原型', '交互设计', '国内'],
    url: 'https://www.modao.cc',
  },

  // UI/UX设计 - 设计系统
  {
    id: 'material-design',
    name: 'Material Design',
    description: 'Google推出的设计系统',
    icon: 'Grid',
    category: '设计资源',
    tags: ['设计系统', 'Google', '规范'],
    url: 'https://m3.material.io',
  },
  {
    id: 'fluent-design',
    name: 'Fluent Design',
    description: '微软推出的流畅设计系统',
    icon: 'Grid',
    category: '设计资源',
    tags: ['设计系统', '微软', '规范'],
    url: 'https://fluent2.microsoft.design',
  },

  // UI/UX设计 - 素材资源
  {
    id: 'dribbble',
    name: 'Dribbble',
    description: '全球顶尖设计师作品分享社区',
    icon: 'Image',
    category: '设计资源',
    tags: ['素材', '设计灵感', '社区'],
    url: 'https://dribbble.com',
  },
  {
    id: 'behance',
    name: 'Behance',
    description: 'Adobe旗下的创意设计作品展示平台',
    icon: 'Image',
    category: '设计资源',
    tags: ['素材', '设计灵感', 'Adobe'],
    url: 'https://www.behance.net',
  },

  // 代码托管 & 协作 - 团队协作
  {
    id: 'discord',
    name: 'Discord',
    description: '流行的社区和团队语音文字沟通工具',
    icon: 'Users',
    category: '协作工具',
    tags: ['团队协作', '沟通', '社区'],
    url: 'https://discord.com',
  },
  {
    id: 'wecom',
    name: '企业微信',
    description: '腾讯出品的企业沟通和协作工具',
    icon: 'Users',
    category: '协作工具',
    tags: ['团队协作', '办公', '国内'],
    url: 'https://work.weixin.qq.com',
  },

  // 代码托管 & 协作 - 代码Review
  {
    id: 'sonarqube',
    name: 'SonarQube',
    description: '代码质量持续检测平台',
    icon: 'Eye',
    category: '协作工具',
    tags: ['代码review', '质量检测', '静态分析'],
    url: 'https://www.sonarqube.org',
  },
  {
    id: 'codecov',
    name: 'Codecov',
    description: '代码覆盖率测试报告工具',
    icon: 'Eye',
    category: '协作工具',
    tags: ['代码review', '测试', '覆盖率'],
    url: 'https://about.codecov.io',
  },

  // 代码托管 & 协作 - CI/CD
  {
    id: 'github-actions',
    name: 'GitHub Actions',
    description: 'GitHub内置的CI/CD自动化工作流工具',
    icon: 'Repeat',
    category: '协作工具',
    tags: ['CI/CD', '自动化', 'GitHub'],
    url: 'https://github.com/features/actions',
  },
  {
    id: 'gitlab-ci',
    name: 'GitLab CI/CD',
    description: 'GitLab内置的持续集成和部署工具',
    icon: 'Repeat',
    category: '协作工具',
    tags: ['CI/CD', '自动化', 'GitLab'],
    url: 'https://docs.gitlab.com/ee/ci',
  },

  // 代码托管 & 协作 - 文档协作
  {
    id: 'confluence',
    name: 'Confluence',
    description: 'Atlassian出品的企业级知识管理和协作平台',
    icon: 'FileEdit',
    category: '协作工具',
    tags: ['文档协作', '知识库', '企业级'],
    url: 'https://www.atlassian.com/software/confluence',
  },
  {
    id: 'ones',
    name: 'ONES Wiki',
    description: '国内研发管理工具ONES的知识库产品',
    icon: 'FileEdit',
    category: '协作工具',
    tags: ['文档协作', '知识库', '国内'],
    url: 'https://ones.ai/product/wiki.html',
  },

  // 学习资源 & 文档 - 视频教程
  {
    id: 'bilibili',
    name: '哔哩哔哩',
    description: '国内最大的学习和视频分享平台，教程丰富',
    icon: 'PlayCircle',
    category: '文档教程',
    tags: ['教程', '视频', '国内'],
    url: 'https://www.bilibili.com',
  },
  {
    id: 'imooc',
    name: '慕课网',
    description: '国内专业的IT技能学习平台',
    icon: 'PlayCircle',
    category: '文档教程',
    tags: ['教程', '编程', '职业教育'],
    url: 'https://www.imooc.com',
  },

  // 学习资源 & 文档 - 面试刷题
  {
    id: 'acwing',
    name: 'AcWing',
    description: '专业的算法学习和竞赛平台',
    icon: 'CheckSquare',
    category: '文档教程',
    tags: ['面试', '刷题', '算法'],
    url: 'https://www.acwing.com',
  },
  {
    id: 'luogu',
    name: '洛谷',
    description: '国内知名的信息学竞赛刷题平台',
    icon: 'CheckSquare',
    category: '文档教程',
    tags: ['面试', '刷题', '信息学竞赛'],
    url: 'https://www.luogu.com.cn',
  },

  // 学习资源 & 文档 - 技术博客
  {
    id: 'csdn',
    name: 'CSDN',
    description: '国内知名的专业IT技术社区',
    icon: 'FileText',
    category: '文档教程',
    tags: ['博客', '技术社区', '国内'],
    url: 'https://blog.csdn.net',
  },
  {
    id: 'hashnode',
    name: 'Hashnode',
    description: '国际开发者技术博客和社区平台',
    icon: 'FileText',
    category: '文档教程',
    tags: ['博客', '技术', '国际'],
    url: 'https://hashnode.com',
  },

  // 学习资源 & 文档 - 编程挑战
  {
    id: 'codewars',
    name: 'Codewars',
    description: '通过挑战来提高编程技能的平台',
    icon: 'Award',
    category: '文档教程',
    tags: ['编程挑战', '算法', '练习'],
    url: 'https://www.codewars.com',
  },
  {
    id: 'exercism',
    name: 'Exercism',
    description: '免费的编程语言练习和指导平台',
    icon: 'Award',
    category: '文档教程',
    tags: ['编程挑战', '练习', '免费'],
    url: 'https://exercism.org',
  },

  // 效率工具 - 思维导图
  {
    id: 'xmind',
    name: 'XMind',
    description: '流行的思维导图和头脑风暴工具',
    icon: 'GitMerge',
    category: '效率工具',
    tags: ['思维导图', '效率', '办公'],
    url: 'https://xmind.cn',
  },
  {
    id: 'mindmaster',
    name: 'MindMaster',
    description: '亿图出品的跨平台思维导图软件',
    icon: 'GitMerge',
    category: '效率工具',
    tags: ['思维导图', '效率', '办公'],
    url: 'https://www.edrawsoft.cn/mindmaster',
  },

  // 效率工具 - 密码管理
  {
    id: '1password',
    name: '1Password',
    description: '知名的跨平台密码管理工具',
    icon: 'Key',
    category: '效率工具',
    tags: ['密码管理', '安全', '跨平台'],
    url: 'https://1password.com',
  },
  {
    id: 'bitwarden',
    name: 'Bitwarden',
    description: '开源免费的密码管理工具',
    icon: 'Key',
    category: '效率工具',
    tags: ['密码管理', '开源', '免费'],
    url: 'https://bitwarden.com',
  },

  // 效率工具 - 翻译工具
  {
    id: 'deepl',
    name: 'DeepL',
    description: 'AI翻译工具，翻译质量媲美人工',
    icon: 'Languages',
    category: '效率工具',
    tags: ['翻译', 'AI', '高精度'],
    url: 'https://www.deepl.com/translator',
  },
  {
    id: 'google-translate',
    name: 'Google 翻译',
    description: 'Google免费在线翻译服务，支持100+语言',
    icon: 'Languages',
    category: '效率工具',
    tags: ['翻译', '免费', '多语言'],
    url: 'https://translate.google.cn',
  },

  // 社区 & 资讯 - 资讯平台
  {
    id: 'infoq',
    name: 'InfoQ',
    description: '促进软件开发领域知识与创新的传播',
    icon: 'Newspaper',
    category: '技术资讯',
    tags: ['资讯', '技术', '架构'],
    url: 'https://www.infoq.cn',
  },
  {
    id: 'oschina',
    name: '开源中国',
    description: '国内最大的开源技术社区',
    icon: 'Newspaper',
    category: '技术资讯',
    tags: ['资讯', '开源', '国内'],
    url: 'https://www.oschina.net',
  },

  // 社区 & 资讯 - 求职招聘
  {
    id: 'boss',
    name: 'BOSS直聘',
    description: '招聘求职找工作，直接跟老板谈',
    icon: 'Briefcase',
    category: '技术资讯',
    tags: ['求职', '招聘', '国内'],
    url: 'https://www.zhipin.com',
  },
  {
    id: 'lagou',
    name: '拉勾网',
    description: '专注互联网行业的求职招聘平台',
    icon: 'Briefcase',
    category: '技术资讯',
    tags: ['求职', '招聘', '互联网'],
    url: 'https://www.lagou.com',
  },

  // 社区 & 资讯 - 开源活动
  {
    id: 'github-explore',
    name: 'GitHub Explore',
    description: '发现GitHub上热门的开源项目',
    icon: 'Calendar',
    category: '技术资讯',
    tags: ['开源活动', '项目', 'GitHub'],
    url: 'https://github.com/explore',
  },
  {
    id: 'hacktoberfest',
    name: 'Hacktoberfest',
    description: '一年一度的全球开源贡献活动',
    icon: 'Calendar',
    category: '技术资讯',
    tags: ['开源活动', '全球', '年度'],
    url: 'https://hacktoberfest.com',
  },
]
